# 1. Ổ cứng (PVC) để lưu file Notebooks và Data không bị mất
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-workspace-pvc
  namespace: odc-system
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi

---
# 2. Động cơ chạy Jupyter Lab
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  namespace: odc-system
spec:
  replicas: 1 # Jupyter mặc định chỉ chạy 1 Pod
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter
          image: aub2205926/my-custom-jupyter:1.0 # Trỏ đúng tên image bạn vừa build
          imagePullPolicy: IfNotPresent # Bắt K8s dùng image cục bộ
          # Tách command và các tham số ra cho đúng chuẩn K8s
          command: ["jupyter", "lab"]
          args:
            - "--ip=0.0.0.0"
            - "--port=8888"
            - "--no-browser"
            - "--allow-root"
            - "--NotebookApp.token=$(JUPYTER_TOKEN)"
          ports:
            - containerPort: 8888
          env:
            # Lấy token từ Secret
            - name: JUPYTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: odc-secrets
                  key: JUPYTER_TOKEN

            # Cấu hình CSDL (K8s cho phép ghép chuỗi biến bằng cú pháp $(VAR) )
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: odc-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odc-secrets
                  key: DB_PASSWORD
            - name: DB_HOSTNAME
              value: "postgres-svc"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "opendatacube"

            - name: ODC_DEFAULT_INDEX_DRIVER
              value: "postgis"
            - name: DATACUBE_INDEX_DRIVER
              value: "postgis"
            # Ghép chuỗi URL
            - name: ODC_DEFAULT_DB_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOSTNAME):$(DB_PORT)/$(DB_DATABASE)"
            - name: DATACUBE_DB_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOSTNAME):$(DB_PORT)/$(DB_DATABASE)"

          volumeMounts:
            # Mount toàn bộ không gian làm việc vào ổ cứng vĩnh cửu
            - name: workspace
              mountPath: /home/jovyan/work
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: jupyter-workspace-pvc

---
# 3. Service (Mở cổng ra ngoài để bạn dùng trình duyệt truy cập)
apiVersion: v1
kind: Service
metadata:
  name: jupyter-svc
  namespace: odc-system
spec:
  # Nếu dùng Docker Desktop, LoadBalancer sẽ tự động map ra localhost của máy bạn
  type: LoadBalancer
  selector:
    app: jupyter
  ports:
    - port: 8888
      targetPort: 8888
