FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    gdal-bin \
    libgdal-dev \
    libpq-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

ENV GDAL_CONFIG=/usr/bin/gdal-config

RUN pip install --no-cache-dir \
    datacube==1.9.18 \
    psycopg2-binary \
    odc-geo \
    odc-stac

WORKDIR /app