apiVersion: v1
kind: Secret
metadata:
  name: odc-secrets
  namespace: odc-system
type: Opaque
# Dùng stringData để K8s tự động mã hóa sang Base64
stringData: 
  DB_USER: "opendatacube"
  DB_PASSWORD: "opendatacubepassword"
  MINIO_USER: "minioadmin"
  MINIO_PASSWORD: "minioadmin123"
  JUPYTER_TOKEN: "opendatacube"