apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odc-ingress
  namespace: odc-system
spec:
  ingressClassName: nginx
  rules:
    # 1. ODC Explorer (Datacube Explorer Web UI)
    - host: explorer.odc-server.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: odc-explorer-svc
                port:
                  number: 8080

    # 2. Jupyter hub
    - host: jupyter.odc-server.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jupyterhub-proxy-public-svc
                port:
                  number: 8000

    # 3. MinIO Dashboard
    - host: minio.odc-server.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-svc
                port:
                  number: 9001
