apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odc-system
resources:
  - namespace.yaml
  - 01-secrets.yaml
  - 02-postgres-core.yaml
  - 03-minio-storage.yaml
  - 04-odc-server.yaml
  - 05-jupyter.yaml
  - 06-ingress.yaml
