apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odc-system
resources:
  - namespace.yaml
  - 01-postgres-core.yaml
  - 02-minio-storage.yaml
  - 03-odc-server.yaml
  - 04-jupyter-rbac.yaml
  - 05-jupyter-hub.yaml
  - 06-jupyter-proxy.yaml
  - 07-ingress.yaml
  - 08-odc-explorer.yaml

configMapGenerator:
  - name: jupyterhub-config
    files:
      - jupyterhub_config.py
