apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odc-system
resources:
  - ../../base
images:
  - name: aub2205926/my-custom-odc
    newTag: "1.9.18"
  - name: aub2205926/my-custom-jupyter
    newTag: "1.0"
patches:
  - target:
      kind: Service
      name: jupyter-svc
    path: jupyter-service-patch.yaml
  - target:
      kind: Service
      name: minio-svc
    path: minio-service-patch.yaml
